version: '3.3'
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # backend:
  #   build: 
  #     context: ./bookshop
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   depends_on:
  #     - db
  #   volumes:
  #     - media_volume:/app/media
  #   ports:
  #     - "8000:8000"

volumes:
  pg_data:
  # static_volume:
  media_volume: