version: '3.3'
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: vanyatheman/bookshop:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_volume:/app/media
    ports:
      - "8000:8000"

volumes:
  pg_data:
  media_volume:
