# Generated by Django 3.2 on 2024-06-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
